version: '3'
services:
  client:
    container_name: todoapp-frontend
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/vite.config.ts:/app/vite.config.js
    networks:
      - client-net
    command: npm run dev
    restart: unless-stopped
  api:
    container_name: todoapp-backend
    build:
      context: api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    environment:
      - PORT=5000
      - NODE_ENV=development
    networks:
      - api-net
      - client-net
    command: npm run dev
    restart: unless-stopped
  db:
    image: mongo:8.0.4
    container_name: todoapp-db
    env_file:
      - ./api/.env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongodata:/data/db
    networks:
      - api-net
volumes:
  mongodata:
networks:
  api-net:
  client-net:
