version: '3'
services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
    networks:
      - api-net
      - client-net
    command: npm run dev
  client:
    build:
      context: ../client
    container_name: api-services
    ports:
      - "3000:3000"
    volumes:
      - ../client:/client
      - /client/node_modules
    networks:
      - client-net
    command: npm run dev
  db:
    image: mongo:8.0.4
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_HOSTNAME: $MONGO_HOSTNAME
    volumes:
      - mongo-data:/data/db
    networks:
      - api-net
volumes:
  mongo-data:
networks:
  api-net:
  client-net:
