version: '3'
services:
  client:
    container_name: todoapp-frontend
    build:
      context: ../client
      dockerfile: ../client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../client:/client
      - ./client/vite.config.ts:/app/vite.config.js
    networks:
      - client-net
    command: npm run dev-exposed
    restart: unless-stopped
  api:
    container_name: todoapp-backend
    build:
      context: .
      #dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    depends_on:
      - dbmongo
    ports:
      - "5000:5000"
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
    links:
      - dbmongo
    networks:
      - api-net
      - client-net
    command: npm run dev
    restart: unless-stopped
  dbmongo:
    container_name: todoapp-db
    image: mongo:8.0.4
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - mongodata:/data/db
    networks:
      - api-net
volumes:
  mongodata:
networks:
  api-net:
  client-net:
